### ISSUE TITLE
Problem with end of list

### ISSUE THREAD

**Issue by mmitch** [perlancar/perl-Org-Parser#6]
There seems to be a problem detecting the end of a list. With a test document like this
```
This is paragraph A.

This is paragraph B.

 + list item 1
 + list item 2
 + list item 3


This is paragraph C after the list has ended.
```
paragraph C will be contained in the 3rd list item rather than being another Org::Element::Text outside of the Org::Element::List.

Dumping the structure shows this:
```
$ perl dump-org-structure < test.org 
Document:
  Text: "This is paragraph A.\n\nThis is paragraph B.\n\n"
  List: U(+) indent=1
    ListItem: +
      (children)
      Text: "list item 1\n"
    ListItem: +
      (children)
      Text: "list item 2\n"
    ListItem: +
      (children)
      Text: "list item 3\n\n\nThis is paragraph C after the lis..."
```

Is there a way to explicitely tell Org::Parser "the current list has ended"?
(I'm new to org mode in general and it seems, that a list is ended by either resetting the indentation or using two empty lines)

Regards,
Christian

**Comment by perlancar** [comment]
Sorry, missed this PR/issue (didn't receive notification from GitHub).

Since this is also discussed in the RT ( https://rt.cpan.org/Ticket/Display.html?id=114621 ) I'm closing this issue as duplicate.

I've started hacking a few months ago, the haven't got the time to finish it. In general, I'd like to overhaul the parser to properly do precedence (i.e. a headlines/entry have the highest precedence and a block or drawer cannot contain a headline, and so on; lists are further down on the precedence order).

**Comment by mmitch** [comment]
Thanks for the update!
Looking forward to it :+1:
